### ISSUE TITLE
no Invoke-WslStatic

### ISSUE THREAD

**Issue by roelarents** [wikiped/WSL-IpHandler#11]
```
> wsl
wsl: The term 'Invoke-WslStatic' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

It was [removed in v8.0.0](https://github.com/wikiped/WSL-IpHandler/commit/47d23#diff-fec55756397d3940254d0331dd6ade9e8c6c962d4d5bf7f0fc408ec49391bf83L926) but still set as alias for wsl.

**Comment by wikiped** [comment]
Thank you for reporting this. It must have been lost during refactoring. It was not intentional. It has been restored in Version 0.9.2.
