### ISSUE TITLE
issue with IpAddressToString

### ISSUE THREAD

**Issue by cptkirkh** [wikiped/WSL-IpHandler#17]
I get  this error after i go through all of the steps and try to edit the interface.
` Install-WslIpHandler -WslInstanceName Ubuntu -GatewayIpAddress 192.168.0.1
PowerShell installing Wsl-IpHandler to Ubuntu...
Install-WslIpHandler: The property 'IPAddressToString' `cannot` be found on this object. Verify that the property exists.`

**Comment by wikiped** [comment]
Thank you for reporting this.

I have pushed a new commit with `Version 0.14.8` that should fix this issue.
