### ISSUE TITLE
Prefix length is not applied to WSL instance when operating in static mode

### ISSUE THREAD

**Issue by Chaoses-Ib** [wikiped/WSL-IpHandler#18]
WSL IP Handler:
`Install-WslIpHandler -GatewayIpAddress 10.0.0.1 -WslInstanceName Ubuntu -WslInstanceIpAddress 10.0.0.2 -UseScheduledTaskOnUserLogOn -DontModifyPsProfile`
WSL (after reboot Windows):
```sh
$ ip addr
...
6: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:15:5d:c4:65:e4 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.2/32 scope global eth0:wsliphndlr
       valid_lft forever preferred_lft forever
    inet6 fe80::215:5dff:fec4:65e4/64 scope link
       valid_lft forever preferred_lft forever
```
As you can see, the prefix length is 32 rather than 24.

In wsl-iphandler.sh:
```sh
# Process Local IP and Host
local ip_address
ip_address=$(get_config 'static_ip' '')
echo_debug "ip_address=$ip_address"

# Get IP address for this WSL Instance
local wsl_ip_address
if [[ "$ip_address" ]]
then
	wsl_ip_address="$ip_address"
	echo_debug "wsl_ip_address=$wsl_ip_address"
else
	local gateway_ip
	gateway_ip=$(get_default_gateway_ip)
	test $? = 0 || error "${LINENO}" "'get_default_gateway_ip' failed." 10
	echo_debug "gateway_ip=$gateway_ip"

	local gateway_prefix
	gateway_prefix=$(get_gateway_prefix_length)
	test $? = 0 || error "${LINENO}" "'get_gateway_prefix_length' failed." 11
	echo_debug "gateway_prefix=$gateway_prefix"

	local gateway_ip_with_prefix
	gateway_ip_with_prefix="$gateway_ip/$gateway_prefix"
	test -n "$gateway_ip_with_prefix" || error "${LINENO}" "No gateway IP found!" 12
	echo_debug "gateway_ip_with_prefix=$gateway_ip_with_prefix"

	local offset
	offset=$(get_config 'ip_offset')
	echo_debug "offset=$offset"
	wsl_ip_address="$(get_new_ip_with_prefix_from_offset "$gateway_ip_with_prefix" "$offset")"
	echo_debug "wsl_ip_address=$wsl_ip_address"
fi

# Register new WSL Instance IP address (i.e. ip addr add ...)
echo_verbose "Adding IP: $wsl_ip_address to dev: $dev ..."
add_wsl_ip_address "$wsl_ip_address"
```
And /etc/wsl.conf:
```
$ cat /etc/wsl.conf
[network]
static_ip = 10.0.0.2
wsl_host = Ubuntu
windows_host = windows
```
As static_ip doesn't contain a prefix length, the add_wsl_ip_address will finally run `ip addr add 10.0.0.2 ...` and thus the prefix length will become 32.

It's easy to manually fix it by changing static_ip to `10.0.0.2/24`. I‘m not sure whether it's by design or a bug, so I just report it here.

**Comment by wikiped** [comment]
If I understand you correctly:

Currently the module assigns static IP to a WSL instance without specifying prefix length, which means the default value of 32 is used.

And it seems you suggest a feature that the module should allow the user to specify a prefix length value that will be used when running `ip addr add ... ` on a WSL instance.

In theory I see no obstacles for this feature to be implemented, but I feel like I am missing the point: Why would one need to have prefix other than 32 on a WSL isntance's IP address, (mind you this is not a __gateway__ IP address), what practical use does it have?

**Comment by Chaoses-Ib** [comment]
In my case, I want the VMware virtual machines and the WSL instances to be under the same subnet. This can be done through WSL IP Handler and bridging the VMware network to the WSL virtual switch. To access VMware VMs from the WSL instances, the prefix length can't be 32, but 24. That's why I need to fix it.
Now I find a way that suits my needs better - using WSL bridged mode described in https://github.com/microsoft/WSL/issues/4150#issuecomment-1018524753. By bridging WSL to VMware virtual network, WSL instances can be under the same subnet as the VMware VMs and access them.
Thanks for your work and reply. Since this issue is by design and not a bug, I'll close it.
