### ISSUE TITLE
Error parsing windows hosts file: 'You cannot call a method on a null-valued expression' in Get-IpAddressHostsCommentTuple

### ISSUE THREAD

**Issue by Firsh** [wikiped/Wsl-IpHandler#22]
```
PS C:\Users\Firsh> Install-WslIpHandler -WslInstanceName Ubuntu -GatewayIpAddress 172.16.0.1 -WslInstanceIpAddress 172.16.0.2 -UseScheduledTaskOnUserLogOn -DontModifyPsProfile
PowerShell installing Wsl-IpHandler to Ubuntu...
[sudo] password for firsh:
Get-IpAddressHostsCommentTuple: N:\Dokumentumok\PowerShell\Modules\Wsl-IpHandler\Scripts\Powershell\FunctionsHostsFile.ps1:261
Line |
 261 |  … stingIp, $existingHosts, $comment = Get-IpAddressHostsCommentTuple $_
     |                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

PowerShell finished installation of Wsl-IpHandler to Ubuntu with Errors:

Pinging Ubuntu from Windows failed:
Ping request could not find host Ubuntu. Please check the name and try again.

**Comment by wikiped** [comment]
Thanks for reporting this error.

It might have something to do with your windows hosts file (potentially malformed?).

Would you be able to post its content? 

Below is Powershell command to print it:

```powershell

cat $env:windir\System32\drivers\etc\hosts

```

**Comment by Firsh** [comment]
I can't post it as it includes some personal information, but it is a mess, thanks for pointing me in the right direction. It has mixed spaces and tabs, but most importantly has entries where for 1 IP I have multiple hosts, separated by a space. So if this is unsupported, that could be a reason:

``192.168.190.190 project1.example.com project2.example.com``

**Comment by wikiped** [comment]
This line will be parsed without any problems:

  > `192.168.190.190 project1.example.com project2.example.com`

There must other lines which are malformed.

Anyway, I have pushed a [commit](https://github.com/wikiped/WSL-IpHandler/commit/5216c8793eb169b6949f9e0b139d0735815fb921) which should mitigate the problem. Please try again after [updating](https://github.com/wikiped/WSL-IpHandler#how-to-update-this-module)  the module.

**Comment by mehrangta** [comment]
> I can't post it as it includes some personal information, but it is a mess, thanks for pointing me in the right direction. It has mixed spaces and tabs, but most importantly has entries where for 1 IP I have multiple hosts, separated by a space. So if this is unsupported, that could be a reason:
> 
> `192.168.190.190 project1.example.com project2.example.com`

I get the same error any workaround you did to fix it ?

**Comment by wikiped** [comment]
@mehrangta

  > I get the same error

What version are you using? There was an update fixing this issue.
