### ISSUE TITLE
All Ubuntu and Fedora based families should be supported

### ISSUE THREAD

**Issue by wikiped** [wikiped/Wsl-IpHandler#26]
Currently (v0.14.13 and earlier) the module will throw an error if `ID` in `/etc/os-release` is not matching exactly `ubuntu` and `fedora`.

It is reasonable to expect that any Ubuntu or Fedora based OS should not fail.

**Comment by erythana** [comment]
Sorry for the delayed update. I updated it again and the distro is now valid. Unfortunately, i found another problem:
![image](https://user-images.githubusercontent.com/42657063/176119084-e1b6eac7-1f16-4cfb-b7cf-84393abdb960.png)

**Comment by wikiped** [comment]
Last comment moved to #29
